"$schema" = "../schemas/schema.json"

[[permission]]
identifier = "allow-commit-upload-buffer"
description = "Enables the commit_upload_buffer command without any pre-configured scope."
[permission.commands]
allow = ["commit_upload_buffer"]
deny = []
[permission.scope]
allow = [{ windows = ["*"] }]

[[permission]]
identifier = "deny-commit-upload-buffer"
description = "Denies the commit_upload_buffer command without any pre-configured scope."
[permission.commands]
allow = []
deny = ["commit_upload_buffer"]
