"$schema" = "../schemas/schema.json"

[[permission]]
identifier = "allow-memio-read"
description = "Allows reading data from shared memory buffer"
[permission.commands]
allow = ["memio_read"]
deny = []
[permission.scope]
allow = [{ windows = ["*"] }]

[[permission]]
identifier = "deny-memio-read"
description = "Denies reading data from shared memory buffer"
[permission.commands]
allow = []
deny = ["memio_read"]
