"$schema" = "../schemas/schema.json"

[[permission]]
identifier = "allow-memio-upload"
description = "Allows uploading files to shared memory buffer"
[permission.commands]
allow = ["memio_upload"]
deny = []
[permission.scope]
allow = [{ linux = ["*"] }, { android = ["*"] }]

[[permission]]
identifier = "deny-memio-upload"
description = "Denies uploading files to shared memory buffer"
[permission.commands]
allow = []
deny = ["memio_upload"]
