"$schema" = "../schemas/schema.json"

[[permission]]
identifier = "allow-send-download-buffer"
description = "Enables the send_download_buffer command without any pre-configured scope."
[permission.commands]
allow = ["send_download_buffer"]
deny = []
[permission.scope]
allow = [{ windows = ["*"] }]

[[permission]]
identifier = "deny-send-download-buffer"
description = "Denies the send_download_buffer command without any pre-configured scope."
[permission.commands]
allow = []
deny = ["send_download_buffer"]
